[package]
name = "react_hooks_in_300_lines_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_mut = "0.1.0"
